### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by naveenmittal04** [ford-prefect/xml2ucm#2]
Running
To build with the example, you could do something like:

$ stack exec xml2ucm -m examples/mako-mixer_paths.xml -c examples/mako-config.xml -o examples
The generated files will be in examples/apq8064-tabla-snd-card/.
[Getting error]
Invalid option -m

stack version 1.5.1

**Comment by ford-prefect** [comment]
@naveenmittal04 you need to use:

```
$ stack exec -- xml2ucm -m examples/mako-mixer_paths.xml -c examples/mako-config.xml -o examples
```

This seems to be a change in stack behaviour. I've updated the README to reflect that now.

**Comment by ford-prefect** [comment]
Thanks for the report, do let me know if you see any other issues or need help.
